"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { completeStaffPasswordChangeAction } from "@/app/actions/auth-profile";
export default function ChangeStaffPasswordPage(){
 const router=useRouter();const [password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");if(password.length<10){setMessage("Use at least 10 characters.");return}if(password!==confirm){setMessage("Passwords do not match.");return}setBusy(true);const {error}=await createSupabaseBrowserClient().auth.updateUser({password});if(error){setBusy(false);setMessage(error.message);return}const result=await completeStaffPasswordChangeAction();setBusy(false);if(!result.ok){setMessage(result.message);return}router.replace("/auth/continue");router.refresh()}
 return <main className="grid min-h-screen place-items-center bg-canvas px-4"><form onSubmit={submit} className="w-full max-w-md rounded-lg border border-line bg-white p-6 shadow-soft"><h1 className="text-2xl font-bold text-navy">Change temporary password</h1><p className="mt-2 text-sm text-muted">Set a new password before continuing to your staff dashboard.</p><label className="mt-5 block text-sm text-muted">New password<input required type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label><label className="mt-4 block text-sm text-muted">Confirm new password<input required type="password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label>{message&&<p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}<button disabled={busy} className="mt-5 w-full rounded-lg bg-navy px-4 py-2.5 font-semibold text-white disabled:opacity-50">{busy?"Updating...":"Update Password"}</button></form><form action="/auth/signout" method="post" className="mt-3 text-center"><button className="text-sm text-accent">Sign out</button></form></main>
}
