"use client";

import { useCallback, useEffect, useState } from "react";
import { sendStaffInvitationAction, listFacultyRoleRequestsAction, reviewFacultyRoleRequestAction, searchAdminUsersAction, setAdminUserActiveAction, setAdminUserRoleAction } from "@/app/actions/admin";
import { AppShell } from "@/components/layout/AppShell";
import { useDemo } from "@/components/od/DemoProvider";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type UserRow = { id: string; name: string; email: string; role: string; registerNumber: string | null; department: string; isActive: boolean };
type RequestRow = { id: string; email: string; reason: string; status: string; createdAt: string; requester: string; department: string };

export default function AdminUsersPage() {
  const { currentUser } = useDemo();
  const [users, setUsers] = useState<UserRow[]>([]), [requests, setRequests] = useState<RequestRow[]>([]), [departments, setDepartments] = useState<{id:string;name:string}[]>([]);
  const [query, setQuery] = useState(""), [email, setEmail] = useState(""), [role, setRole] = useState<"faculty"|"hod">("faculty"), [departmentId, setDepartmentId] = useState("");
  const [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [u,r] = await Promise.all([searchAdminUsersAction(query), listFacultyRoleRequestsAction()]); if(u.ok)setUsers(u.data);else setMessage(u.message); if(r.ok)setRequests(r.data);else setMessage(r.message); }, [query]);
  useEffect(() => { let live = true; createSupabaseBrowserClient().from("departments").select("id,name").eq("code","ECE").eq("is_active",true).then(({data})=>{if(live&&data){setDepartments(data);setDepartmentId(data[0]?.id??"")}}); return()=>{live=false}; }, []);
  useEffect(() => { const t=window.setTimeout(()=>void load(),150); return()=>window.clearTimeout(t); }, [load]);
  async function invite() { setBusy(true); setMessage(""); const result=await sendStaffInvitationAction({email,role,departmentId}); setBusy(false); if(!result.ok){setMessage(result.message);return;} setMessage(`Invitation sent to ${result.data.email}. They can create their Faculty/HOD account using the secure link in the email.`); setEmail(""); await load(); }
  async function toggle(user:UserRow){setBusy(true);const result=await setAdminUserActiveAction(user.id,!user.isActive);setBusy(false);if(!result.ok)setMessage(result.message);else await load();}
  async function changeRole(user:UserRow,nextRole:"student"|"faculty"|"hod"){if(nextRole===user.role)return;setBusy(true);setMessage("");const result=await setAdminUserRoleAction(user.id,nextRole);setBusy(false);if(!result.ok)setMessage(result.message);else await load();}
  async function review(item:RequestRow,approved:boolean){setBusy(true);setMessage("");const result=await reviewFacultyRoleRequestAction(item.id,approved);setBusy(false);if(!result.ok)setMessage(result.message);else{if(result.data.email)setMessage(`Invitation sent to ${result.data.email}.`);await load();}}
  return <AppShell user={currentUser}>
    <h2 className="text-2xl font-bold text-navy">User Management</h2><p className="mt-1 text-sm text-muted">Invite ECE Faculty or HOD accounts by email. Their role and department are fixed by this invitation.</p>
    {message&&<p role="status" className="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}
    <section className="mt-5 rounded-lg border border-line bg-white p-5 shadow-soft"><h3 className="font-bold text-navy">Invite Faculty / HOD</h3><p className="mt-1 text-sm text-muted">We’ll email a secure one-time link. The invitee verifies their SRMIST address, then sets their name, Faculty ID, and password on this website. If an invitation link expires, enter the same email, role, and department here to issue a fresh link; only incomplete invited accounts can be restarted.</p><form onSubmit={e=>{e.preventDefault();void invite()}}><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-sm text-muted">SRMIST email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded-lg border border-line px-3 py-2" placeholder="name@srmist.edu.in"/></label><label className="text-sm text-muted">Role<select value={role} onChange={e=>setRole(e.target.value as "faculty"|"hod")} className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option value="faculty">Faculty</option><option value="hod">HOD</option></select></label><label className="text-sm text-muted">Department<select required value={departmentId} onChange={e=>setDepartmentId(e.target.value)} className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option value="">Select</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><button disabled={!email||!departmentId||busy} className="mt-4 rounded-lg bg-navy px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?"Sending…":"Send Invitation"}</button></form></section>
    <section className="mt-6 rounded-lg border border-line bg-white p-5 shadow-soft"><h3 className="font-bold text-navy">Accounts</h3><input aria-label="Search users" placeholder="Search name, email, register number" value={query} onChange={e=>setQuery(e.target.value)} className="mt-3 w-full max-w-lg rounded-lg border border-line px-3 py-2"/><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted">{["Name","Email","Register No.","Department","Role","Status",""] .map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-line"><td className="p-2">{u.name||"—"}</td><td className="p-2">{u.email}</td><td className="p-2">{u.registerNumber??"—"}</td><td className="p-2">{u.department}</td><td className="p-2">{u.role==="admin"?<span className="font-medium capitalize">{u.role}</span>:<select aria-label={`Role for ${u.name}`} value={u.role as "student"|"faculty"|"hod"} disabled={busy||u.id===currentUser.id} onChange={e=>void changeRole(u,e.target.value as "student"|"faculty"|"hod")} className="rounded-lg border border-line px-2 py-1 capitalize"><option value="student">Student</option><option value="faculty">Faculty</option><option value="hod">HOD</option></select>}</td><td className="p-2">{u.isActive?"Active":"Inactive"}</td><td className="p-2"><button disabled={busy||u.id===currentUser.id} onClick={()=>void toggle(u)} className="text-accent disabled:opacity-40">{u.isActive?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></section>
    <section className="mt-6 rounded-lg border border-line bg-white p-5 shadow-soft"><h3 className="font-bold text-navy">HOD Faculty Role Requests</h3>{requests.filter(r=>r.status==="PENDING").map(r=><article key={r.id} className="mt-3 rounded-lg border border-line p-4 text-sm"><b>{r.email}</b> · requested by {r.requester}<dl className="mt-2 grid gap-1 text-sm text-muted sm:grid-cols-3"><div><dt>Department</dt><dd className="font-medium text-navy">{r.department||"—"}</dd></div><div><dt>Request date</dt><dd className="font-medium text-navy">{new Date(r.createdAt).toLocaleDateString("en-IN")}</dd></div><div><dt>Status</dt><dd className="font-medium text-navy">{r.status}</dd></div></dl><p className="mt-2 text-muted">{r.reason}</p><div className="mt-3 flex gap-2"><button disabled={busy} onClick={()=>void review(r,true)} className="rounded bg-emerald-700 px-3 py-1.5 font-semibold text-white">Approve &amp; Send Invitation</button><button disabled={busy} onClick={()=>void review(r,false)} className="rounded border border-line px-3 py-1.5">Reject</button></div></article>)}{!requests.some(r=>r.status==="PENDING")&&<p className="mt-3 text-sm text-muted">No pending faculty requests.</p>}</section>
  </AppShell>;
}
