"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { useDemo } from "@/components/od/DemoProvider";
import { loadAdminPageData, saveAcademicYearAction, setDepartmentActiveAction, type AdminPageData } from "@/app/actions/admin-data";

type Section = "students" | "faculty" | "hods" | "departments" | "od-limits" | "settings";
const headings: Record<Section, string> = { students: "Students", faculty: "Faculty", hods: "HODs", departments: "Departments", "od-limits": "OD Limits", settings: "Settings" };
const blank: AdminPageData = { users: [], departments: [], years: [], limits: [], stats: {} };

export function AdminDataPage({ section }: { section: Section }) {
  const { currentUser } = useDemo();
  const [data, setData] = useState(blank);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [yearName, setYearName] = useState("");
  const [yearStart, setYearStart] = useState("");
  const [yearEnd, setYearEnd] = useState("");
  const load = useCallback(async () => { const result = await loadAdminPageData(); if (result.ok) { setData(result.data); setError(""); } else setError(result.message); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function toggleDepartment(id: string, active: boolean) { setBusy(true); const result = await setDepartmentActiveAction(id, active); setBusy(false); if (!result.ok) setError(result.message ?? "Could not update department."); else void load(); }
  async function saveYear(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const result = await saveAcademicYearAction({ name: yearName, startDate: yearStart, endDate: yearEnd }); setBusy(false); if (!result.ok) setError(result.message ?? "Could not save academic year."); else { setYearName(""); await load(); } }
  const role = section === "students" ? "student" : section === "faculty" ? "faculty" : section === "hods" ? "hod" : null;
  const members = role ? data.users.filter((user) => user.role === role) : [];

  return <AppShell user={currentUser}>
    <div className="rounded-lg border border-line bg-white p-6 shadow-soft">
      <h2 className="text-2xl font-bold text-navy">{headings[section]}</h2>
      <p className="mt-1 text-sm text-muted">{section === "settings" ? "Current configuration from the active Supabase schema." : `Live ${headings[section].toLowerCase()} records from Supabase.`}</p>
      {error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}
      {role && <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted">{["Name", "Email", "Department", "Role", "Status", "Account / Password"].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{members.map((user) => <tr className="border-b border-line" key={user.id}><td className="p-2 font-medium text-navy">{user.name || "—"}</td><td className="p-2">{user.email}</td><td className="p-2">{user.department}</td><td className="p-2 capitalize">{user.role}</td><td className="p-2">{user.active ? "Active" : "Inactive"}</td><td className="p-2">{user.createdAt ? new Date(user.createdAt).toLocaleDateString() : "—"}{user.role !== "student" ? <span className="block text-xs text-muted">{user.mustChangePassword ? "Password change required" : "Password current"}</span> : null}</td></tr>)}</tbody></table>{!members.length && !error && <p className="py-8 text-center text-sm text-muted">No {headings[section].toLowerCase()} found.</p>}</div>}
      {section === "departments" && <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted"><th className="p-2">Department</th><th className="p-2">Code</th><th className="p-2">Status</th><th className="p-2">Action</th></tr></thead><tbody>{data.departments.map((dept) => <tr key={dept.id} className="border-b border-line"><td className="p-2">{dept.name}</td><td className="p-2">{dept.code}</td><td className="p-2">{dept.active ? "Active" : "Inactive"}</td><td className="p-2"><button disabled={busy} onClick={() => void toggleDepartment(dept.id, !dept.active)} className="font-semibold text-accent disabled:opacity-50">{dept.active ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table>{!data.departments.length && <p className="py-8 text-center text-sm text-muted">No departments found.</p>}</div>}
      {section === "od-limits" && <><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted"><th className="p-2">Department</th><th className="p-2">Code</th><th className="p-2">Academic year</th><th className="p-2">Limit</th><th className="p-2">Year status</th></tr></thead><tbody>{data.limits.map((limit) => <tr key={limit.id} className="border-b border-line"><td className="p-2">{limit.department}</td><td className="p-2">{limit.code}</td><td className="p-2">{limit.year}</td><td className="p-2">{limit.maxOds ?? "Not configured"}</td><td className="p-2">{limit.activeYear ? "Active" : "Inactive"}</td></tr>)}</tbody></table>{!data.limits.length && <p className="py-8 text-center text-sm text-muted">No OD limits have been configured.</p>}</div><p className="mt-3 text-xs text-muted">The installed database migration defines OD limits as read-only configuration. Updates are disabled until an authorized database workflow exists.</p></>}
      {section === "settings" && <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-lg border border-line p-4"><h3 className="font-semibold text-navy">Academic years</h3><p className="mt-1 text-sm text-muted">An active academic year is required before students can submit OD requests. Saving a year makes it the active year.</p><form onSubmit={saveYear} className="mt-4 space-y-3"><label className="block text-sm text-muted">Academic year name<input required minLength={4} maxLength={80} value={yearName} onChange={e=>setYearName(e.target.value)} placeholder="2026–2027" className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm text-muted">Start date<input required type="date" value={yearStart} onChange={e=>setYearStart(e.target.value)} className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label><label className="block text-sm text-muted">End date<input required type="date" min={yearStart||undefined} value={yearEnd} onChange={e=>setYearEnd(e.target.value)} className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label></div><button disabled={busy||!yearName||!yearStart||!yearEnd} className="rounded-lg bg-navy px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Save and activate year"}</button></form>{data.years.length ? <ul className="mt-4 divide-y divide-line">{data.years.map((year) => <li key={year.id} className="py-3 text-sm"><span className="font-medium">{year.name}</span><span className={`ml-2 rounded-full px-2 py-1 text-xs ${year.active ? "bg-emerald-50 text-emerald-800" : "bg-slate-100 text-slate-700"}`}>{year.active ? "Active" : "Inactive"}</span><span className="mt-1 block text-muted">{year.startDate} – {year.endDate}</span></li>)}</ul> : <p className="mt-3 text-sm text-muted">No academic year is configured.</p>}</section><section className="rounded-lg border border-line p-4"><h3 className="font-semibold text-navy">Departments</h3><p className="mt-2 text-sm text-muted">{data.departments.filter((d) => d.active).length} active of {data.departments.length} configured.</p><p className="mt-2 text-sm text-muted">No system_settings or workflow_settings table exists in the installed migration set; this page lists only settings represented by the current schema.</p></section></div>}
    </div>
  </AppShell>;
}
