"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff } from "lucide-react";
import { completeStaffSetupAction, getStaffSetupInfoAction } from "@/app/actions/admin";

export function StaffAccountSetup() {
  const router = useRouter();
  const [email, setEmail] = useState(""), [department, setDepartment] = useState(""), [role, setRole] = useState("");
  const [name, setName] = useState(""), [facultyId, setFacultyId] = useState(""), [password, setPassword] = useState(""), [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false), [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [message, setMessage] = useState("Checking your invitation…"), [busy, setBusy] = useState(false), [ready, setReady] = useState(false);
  useEffect(() => { let alive = true; void getStaffSetupInfoAction().then((result) => { if (!alive) return; if (!result.ok) { setMessage(result.message); return; } setEmail(result.data.email); setDepartment(result.data.department); setRole(result.data.role); setMessage(""); setReady(true); }); return () => { alive = false; }; }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const result = await completeStaffSetupAction({ fullName: name, facultyId, password, confirmPassword }); setBusy(false); if (!result.ok) { setMessage(result.message); return; } router.replace("/auth/continue"); router.refresh(); }
  return <main className="min-h-screen bg-surface px-4 py-12"><section className="mx-auto max-w-2xl rounded-lg border border-line bg-white p-6 shadow-soft"><p className="text-xs font-semibold uppercase tracking-wide text-accent">ECE Department · Secure Invitation</p><h1 className="mt-2 text-2xl font-bold text-navy">Create your staff account</h1><p className="mt-2 text-sm text-muted">This account was invited by an administrator. Your role and department are fixed to that invitation.</p>
    {ready ? <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm text-muted">Staff name<input required minLength={2} maxLength={120} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label><label className="block text-sm text-muted">Staff ID<input required maxLength={120} value={facultyId} onChange={e=>setFacultyId(e.target.value)} placeholder="Faculty identifier" className="mt-1 w-full rounded-lg border border-line px-3 py-2"/><span className="mt-1 block text-xs">Enter the Faculty/HOD ID provided by your department.</span></label><label className="block text-sm text-muted">Staff email<input readOnly value={email} className="mt-1 w-full rounded-lg border border-line bg-slate-50 px-3 py-2"/></label><label className="block text-sm text-muted">Department<input readOnly value={department} className="mt-1 w-full rounded-lg border border-line bg-slate-50 px-3 py-2"/></label><p className="text-sm text-muted">Invited role: <span className="font-semibold capitalize text-navy">{role}</span></p><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm text-muted">Password<span className="relative mt-1 block"><input required minLength={10} maxLength={128} type={showPassword?"text":"password"} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-lg border border-line px-3 py-2 pr-10"/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?"Hide password":"Show password"} className="absolute inset-y-0 right-0 flex items-center px-3 text-muted">{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label><label className="block text-sm text-muted">Confirm password<span className="relative mt-1 block"><input required minLength={10} maxLength={128} type={showConfirmPassword?"text":"password"} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className="w-full rounded-lg border border-line px-3 py-2 pr-10"/><button type="button" onClick={()=>setShowConfirmPassword(value=>!value)} aria-label={showConfirmPassword?"Hide confirm password":"Show confirm password"} className="absolute inset-y-0 right-0 flex items-center px-3 text-muted">{showConfirmPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label></div><button disabled={busy} className="rounded-lg bg-navy px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy?"Creating account…":"Create account"}</button></form> : <p className="mt-6 rounded-lg bg-slate-50 p-4 text-sm text-muted">{message}</p>}
    {message&&ready&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message}</p>}
  </section></main>;
}
